language: scala
scala: 2.11.12

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

sudo: required

services:
  - docker

before_script:
  - docker run -d --rm --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd:v2.9.1-drivers

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:MaxMetaspaceSize=1024M clean scalastyle coverage test coverageReport assembly

after_success:

- bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
